version: "3.9"
services:
  app:
    image: "${TESTING_IMAGE}"
    depends_on:
      - postgres
      - redis
    networks:
      - banknetwork

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpwd
      POSTGRES_DB: bankdb
    networks:
      - banknetwork
    volumes:
      - ./healthchecks:/healthchecks
    healthcheck:
      test: /healthchecks/postgres-healthcheck
      interval: "5s"

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - banknetwork

  check:
    image: alpine/curl:3.14
    depends_on:
      app:
        condition: service_started
    command: curl --fail http://app:3000/v1/health/ping || exit 1

networks:
  banknetwork:

