FROM node:18-slim

# Install procps so the watch mode doesn't crash the container on reload
RUN apt-get update && apt-get -y install procps

# Default port for NestJS
EXPOSE 3001

#Temporary folder for node_modules
WORKDIR /opt/app

#Copy everything into docker
COPY . .

# Install dependencies
RUN yarn install --frozen-lockfile


# Add node_modules bin to the path
ENV PATH=/opt/app/node_modules/.bin:$PATH

# Change permissions of script
RUN chmod +x ./start.sh


ENTRYPOINT ["./start.sh"]
