version: "3.9"
services:
  app:
    build: .
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - seed
    networks:
      - banknetwork

  seed:
    build:
      context: .
      dockerfile: Dockerfile.seed
    ports:
      - 3001:3001
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - banknetwork
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/bankdb

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=bankdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - banknetwork
    volumes:
      - ~/.docker-conf/bank/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    networks:
      - banknetwork

networks:
  banknetwork:
    driver: bridge

secrets:
  db_user:
    file: ./secrets/db_user.txt
  db_name:
    file: ./secrets/db_name.txt
  db_password:
    file: ./secrets/db_password.txt
  pgadmin_email:
    file: ./secrets/pgadmin_email.txt
  pgadmin_password:
    file: ./secrets/pgadmin_password.txt
