version: "3.9"
services:
  app:
    build: .
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    networks:
      - banknetwork
    secrets:
      - db_user
      - db_password

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB_FILE: /run/secrets/db_name
    secrets:
      - db_user
      - db_password
      - db_name
    networks:
      - banknetwork
    volumes:
      - ./healthchecks:/healthchecks
    healthcheck:
      test: /healthchecks/postgres-healthcheck
      interval: "5s"

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - banknetwork

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    networks:
      - banknetwork

networks:
  banknetwork:

secrets:
  db_user:
    file: ./secrets/db_user.txt
  db_name:
    file: ./secrets/db_name.txt
  db_password:
    file: ./secrets/db_password.txt
  pgadmin_email:
    file: ./secrets/pgadmin_email.txt
  pgadmin_password:
    file: ./secrets/pgadmin_password.txt
